
`define RS232_INTERF_CHAN
//`define EXTERNAL_SRAM_EN
//`define VIDEO_640x480_RGB


`define CPU_QUANTITY		5 //4
`define PROC_QUANTITY	20 //7

`define CLK_FREQ_PLL		80 * 1000000

`define MAIN_CLK_FREQ	`CLK_FREQ_PLL / 2

`define FREQ_VIDEO_DIVIDER	((`CLK_FREQ_PLL / 25000000) - 1)

//`define IS_USE_PLL	

//`define IS_USE_FPU	


`define NO_DATA_COUNTER_MAX	32
`define THREAD_SLEEP_TIMEOUT	256


`define INTERNAL_MEM_ADDR_BITS		9 //7
`define INTERNAL_MEM_VALUE		(2**`INTERNAL_MEM_ADDR_BITS) //256 //128 //200
`define INTERNAL_MEM_FILE		"mem.txt"

`define EXTERNAL_PRG_ADDR_E	524288

`define VIDEO1_ADDR_B			`EXTERNAL_PRG_ADDR_E
`define VIDEO1_ADDR_E			`VIDEO1_ADDR_B + 524288  //`VIDEO1_ADDR_B + (640*480)
  
  
`define RAM_TOTAL					`VIDEO1_ADDR_E
  


`define UNMODIFICABLE_ADDR_B	`VIDEO1_ADDR_B


//`define REG_IP  15
`define REG_IP  7


`define THREAD_HEADER_SPACE  2
`define THREAD_REGS_TO_CODE_SPACE  1


`define RS232_DATA_ADDR 'h fffffff0

`define RS232_BAUD_RATE	9600
  
  
//`define PAUSE_PROC_ENABLE 1

`define CHAN_OP_CPUS_TAIL_CUTOFF_ENABLE 1
`define PAUSE_OR_CHAN_OP_TAIL_CUTOFF_ENABLE 1


`define EXTERNAL_CHANNELS_BEGIN 'h f0000000
`define EXTERNAL_CHANNELS_END   'h fffffffe
